import './globals.css'
import { Inter } from 'next/font/google'

import { StylesCSR    } from './StylesCSR'    // client_side_rendering CSS (required)
import { StylesSSR    } from './StylesSSR'    // server_side_rendering CSS (optional)
import { StylesEffect } from './StylesEffect' // common style such as headings, paragraphs, blockquotes, etc

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <head>
                <StylesCSR />
                <StylesSSR />
                <StylesEffect />
            </head>
            <body className={inter.className}>{children}</body>
        </html>
    )
}
